FROM eugeneware/php-5.3
ENV TZ=America/Santiago
#ENV TZ=America/Caracas
COPY . /var/www/html
WORKDIR /var/www/html
EXPOSE 80

# docker build -t sicoremm-image-qa .   
# docker run -p 8085:80 --name sicoremm-qa sicoremm-image-qa