FROM eugeneware/php-5.3
ENV TZ=America/Santiago
#ENV TZ=America/Caracas
COPY . /var/www/html
WORKDIR /var/www/html
EXPOSE 80

# docker build -t sicoremm-image .   
# docker run -p 8080:80 --name sicoremm sicoremm-image




# docker build -t sicoremm-image2 .   
# docker run -p 8081:80 --name sicoremm2 sicoremm-image2